# Generated by Django 5.1.1 on 2024-12-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_alter_user_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
    ]
