# Generated by Django 5.1.1 on 2026-02-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0001_initial'),
    ]

    operations = [
    ]
