# Generated by Django 5.1.1 on 2024-11-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='sport name')),
                ('country', models.CharField(max_length=100, verbose_name='origin country')),
                ('popularity', models.IntegerField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'sports',
                'verbose_name_plural': 'sports',
                'db_table': 'tb_sports',
            },
        ),
    ]
