# Generated by Django 5.1.1 on 2026-02-24 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sportmodels',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sportmodels',
            name='name',
            field=models.CharField(max_length=100, verbose_name='sport name'),
        ),
        migrations.AlterUniqueTogether(
            name='sportmodels',
            unique_together={('user', 'name')},
        ),
    ]
