# Generated by Django 5.1.1 on 2024-12-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True)),
                ('birth_weight', models.IntegerField()),
                ('birth_height', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='F', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BabyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateField()),
                ('amount', models.IntegerField()),
                ('baby_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.babyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BabyDiapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.DateTimeField()),
                ('brand', models.CharField(max_length=100)),
                ('is_leaked', models.BooleanField(default=False)),
                ('baby_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.babyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FeedMilk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_time', models.DateTimeField()),
                ('milk_volume', models.IntegerField()),
                ('time_different', models.DateTimeField(blank=True)),
                ('baby_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.babyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.DateTimeField()),
                ('time_different', models.DateTimeField(blank=True)),
                ('baby_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.babyinfo')),
            ],
        ),
    ]
