# Generated by Django 5.1.1 on 2024-12-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0002_alter_babydiapers_baby_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babydiapers',
            old_name='baby_info',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='babyexpense',
            old_name='baby_info',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='feedmilk',
            old_name='baby_info',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sleeplog',
            old_name='baby_info',
            new_name='user',
        ),
    ]
