# Generated by Django 5.1.1 on 2024-12-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0003_rename_baby_info_babydiapers_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmilk',
            name='time_different',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
