# Generated by Django 5.1.1 on 2024-12-28 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0006_alter_temperaturemodel_temperature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemperatureModel',
            new_name='Temperature',
        ),
    ]
