# Generated by Django 5.1.1 on 2024-12-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0007_rename_temperaturemodel_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
