# Generated by Django 5.1.1 on 2024-12-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0008_alter_temperature_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babydiapers',
            name='is_leaked',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
