# Generated by Django 5.1.1 on 2025-01-05 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0010_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyexpense',
            name='create_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='babyexpense',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='babyexpense',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='babyexpense',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
    ]
