# Generated by Django 5.1.1 on 2025-01-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0011_babyexpense_create_time_babyexpense_name_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='sleeplog',
        #     name='time_different',
        # ),
        migrations.AddField(
            model_name='sleeplog',
            name='duration',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='status',
            field=models.CharField(default='熟睡', max_length=100),
            preserve_default=False,
        ),
    ]
