# Generated by Django 5.1.1 on 2025-01-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0012_remove_sleeplog_time_different_sleeplog_duration_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='sleeplog',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
