# Generated by Django 5.1.1 on 2025-01-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0013_remove_sleeplog_time_different_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='babyexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='babyexpense',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='babyexpense',
            name='order_time',
            field=models.DateTimeField(),
        ),
    ]
