# Generated by Django 5.1.1 on 2025-01-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0014_remove_sleeplog_time_different_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='babyexpense',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
