# Generated by Django 5.1.1 on 2025-01-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0015_remove_sleeplog_time_different_babyexpense_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeplog',
            name='time_different',
        ),
    ]
