# Generated by Django 5.1.1 on 2025-01-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0015_remove_sleeplog_time_different_babyexpense_image_url'),
    ]

    operations = [

        migrations.AddField(
            model_name='sleeplog',
            name='describe',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
