# Generated by Django 5.1.1 on 2025-02-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0016_remove_sleeplog_time_different'),
        ('baby', '0016_remove_sleeplog_time_different_sleeplog_describe'),
    ]

    operations = [
    ]
