# Generated by Django 5.1.1 on 2025-02-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0018_rename_date_temperature_measure_date_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='babydiapers',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='babydiapers',
            name='peeing_color',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='babydiapers',
            name='stool_color',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='babydiapers',
            name='stool_shape',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='babydiapers',
            name='tabActiveName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
