# Generated by Django 5.1.1 on 2025-02-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0019_remove_sleeplog_time_different_babydiapers_describe_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='babydiapers',
            name='tabActiveName',
            field=models.CharField(default='peeing', max_length=100),
        ),
    ]
