# Generated by Django 5.1.1 on 2025-02-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0021_remove_sleeplog_time_different_pantsbrandmodel'),
    ]

    operations = [

        migrations.AlterField(
            model_name='babydiapers',
            name='peeing_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='babydiapers',
            name='stool_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='babydiapers',
            name='stool_shape',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
