# Generated by Django 5.1.1 on 2025-02-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0023_remove_sleeplog_time_different_growingblogmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growingblogmodel',
            name='blog_id',
        )
    ]
