# Generated by Django 5.1.1 on 2026-02-24 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0024_remove_growingblogmodel_blog_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='sleeplog',
        #     name='time_different',
        # ),
        migrations.AddField(
            model_name='babyexpense',
            name='expense_type',
            field=models.CharField(default='expense', max_length=10),
        ),
        migrations.AddField(
            model_name='babyinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
