# Generated by Django 5.1.1 on 2026-02-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0026_remove_sleeplog_time_different_expensetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='baby/'),
        ),
    ]
