# Generated by Django 5.1.1 on 2026-02-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0027_babyinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyinfo',
            name='birth_week',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='babyinfo',
            name='is_only_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='babyinfo',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
