# Generated by Django 5.1.1 on 2026-03-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0029_babyalbum_albumphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmilk',
            name='duration_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedmilk',
            name='feed_type',
            field=models.CharField(default='bottle', max_length=20),
        ),
        migrations.AddField(
            model_name='feedmilk',
            name='left_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedmilk',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedmilk',
            name='right_duration',
            field=models.IntegerField(default=0),
        ),
    ]
