# Generated by Django 5.1.1 on 2026-03-28 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0037_vaccinedefinition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenstrualSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_length', models.IntegerField(default=28)),
                ('period_length', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenstrualLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_period', models.BooleanField(default=False)),
                ('flow_level', models.IntegerField(default=0)),
                ('pain_level', models.IntegerField(default=0)),
                ('had_sex', models.BooleanField(default=False)),
                ('symptoms', models.CharField(blank=True, max_length=500, null=True)),
                ('basal_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mood', models.CharField(blank=True, choices=[('happy', 'happy'), ('good', 'good'), ('normal', 'normal'), ('bad', 'bad'), ('worse', 'worse')], max_length=20, null=True)),
                ('habit_eat_on_time', models.BooleanField(default=False)),
                ('habit_water8', models.BooleanField(default=False)),
                ('habit_fruits', models.BooleanField(default=False)),
                ('habit_exercise', models.BooleanField(default=False)),
                ('habit_poop', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
