# Generated by Django 5.1.1 on 2026-03-29 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0038_menstrualsetting_menstruallog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('calendar_type', models.CharField(choices=[('lunar', 'lunar'), ('solar', 'solar')], default='lunar', max_length=10)),
                ('solar_date', models.DateField(blank=True, null=True)),
                ('lunar_year', models.IntegerField(blank=True, null=True)),
                ('lunar_month', models.IntegerField(blank=True, null=True)),
                ('lunar_day', models.IntegerField(blank=True, null=True)),
                ('lunar_is_leap', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]

