# Generated by Django 5.1.1 on 2026-04-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0040_birthdayrecord_id_card_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdayrecord',
            name='id_card_date',
        ),
    ]
